controllers:
    resource: ../src/Controller/
    type: attribute

#app_home:
#    path: '/'
#    controller: App\Controller\HomeController::index

app_login:
    path: '/login'
    controller: App\Controller\SecurityController::login

app_logout:
    path: '/logout'
    controller: App\Controller\SecurityController::logout

app_register:
    path: '/register'
    controller: App\Controller\RegistrationController::register

app_verify_email:
    path: '/verify/email'
    controller: App\Controller\RegistrationController::verifyUserEmail
    
app_forgot_password_request:
    path: '/reset-password'
    controller: App\Controller\ResetPasswordController::request

app_check_email:
    path: '/reset-password/check-email'
    controller: App\Controller\ResetPasswordController::checkEmail

app_reset_password:
    path: '/reset-password/reset/{token}'
    controller: App\Controller\ResetPasswordController::reset

app_reset_password_new:
    path: '/reset-password/reset'
    controller: App\Controller\ResetPasswordController::reset

#Admin

app_admin_login:
    path: '/admin/login'
    controller: App\Controller\AdminSecurityController::login

app_admin_logout:
    path: '/admin/logout'
    controller: App\Controller\AdminSecurityController::logout

app_admin_dashboard:
    path: '/admin'
    controller: App\Controller\AdminController::index

#Category
app_category_index:
    path:       /admin/category
    controller: App\Controller\CategoryController::index
    methods:    GET

app_category_new:
    path:       /admin/category/new
    controller: App\Controller\CategoryController::new
    methods:    GET|POST

app_category_show:
    path:       /admin/category/{id}
    controller: App\Controller\CategoryController::show
    methods:    GET

app_category_edit:
    path:       /admin/category/{id}/edit
    controller: App\Controller\CategoryController::edit
    methods:    GET|POST

app_category_delete:
    path:       /admin/category/{id}
    controller: App\Controller\CategoryController::delete
    methods:    POST

app_get_sub_category:
    path: /get-categories/{id}
    controller: App\Controller\CategoryController::getCategories
    methods: GET|POST

app_get_all_category:
    path: /get-all
    controller: App\Controller\CategoryController::getAllCategoryMenu
    methods: GET|POST

#Article 
app_article_list:
    path:       /admin/article
    controller: App\Controller\ArticleController::list
    methods:    GET

app_article_new:
    path:       /admin/article/new
    controller: App\Controller\ArticleController::new
    methods:    GET|POST

app_article_edit:
    path:       /admin/article/{id}/edit
    controller: App\Controller\ArticleController::edit
    methods:    GET|POST

app_article_delete:
    path: /admin/article/{id}
    controller: App\Controller\ArticleController::delete
    methods: POST


app_article_display:
    path: /article/{id}
    controller: App\Controller\ArticleController::display
    methods: GET

app_article_like:
    path: /article/like/{id}
    controller: App\Controller\ArticleController::likearticle
    methods: GET|POST


#display routes
app_home:
    path: '/'
    controller: App\Controller\DisplayController::index

app_display:
    path: /display
    controller: App\Controller\DisplayController::index

app_display_article:
    path: /display/{id}
    controller: App\Controller\DisplayController::index
    methods: GET|POST

app_ajax_article:
    path: /listarticle/{id}
    controller: App\Controller\DisplayController::ajaxlist
    methods: GET|POST

app_ajax_advance_search:
    path: /advancesearch
    controller: App\Controller\DisplayController::advanceSearch
    methods: POST
